services:
  postgres:
    container_name: postgres_peach_memo
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: peach_memo_db

    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: on-failure

  mail-dev:
    container_name: mail-dev-peach_memo
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
